# Generated by Django 4.2.6 on 2023-10-24 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_remove_projects_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='image',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
    ]
