zales_kay_jared_selectors = {
    "product_boxes": ["div", {"class": "product-item-inner"}],
    "product_on_sale": ["div", {"class": "other-prices"}],
    "product_href": ["a", {"class": "thumb main-thumb"}],
    "image_src": ["img", {"class": "img-responsive with-border"}],
    "title": ["div", {"class": "name product-tile-description"}],
    "price": ["div", {"class": "price"}],
    "original_price": ["div", {"class": "original-price"}],
}


zales_kay_jared_stone_types = [
    "Diamond",
    "Lab+Created+Diamond",
    "No+Stone",
    "Morganite",
    "Sapphire",
    "Pearl",
    "Emerald",
    "Ruby",
    "Amethyst",
    "Topaz",
    "Opal",
    "Garnet",
    "Peridot",
    "Citrine",
    "Aquamarine",
    "Tanzanite",
    "Other",
    "Quartz",
    "Spinel",
    "Onyx",
    "Multi",
    "Alexandrite",
    "Cubic+Zirconia",
    "Apatite",
    "Crystal",
    "Cultured+Pearl",
    "Mother+of+Pearl",
    "Rhodolite",
    "Aquaprase",
    "Birthstone",
    "Chalcedony",
    "Moonstone",
    "Tourmaline",
    "Turquoise",
    "Zircon",
]

zales_kay_jared_metal_types = [
    "Gold",
    "Sterling+Silver",
    "Platinum",
    "Stainless+Steel",
]

ross_simons_stone_type_sub_class = [
    "gemstones",
    "diamond",
    "perals",
    "faux_stone",
    "other_stones",
]

ross_simons_stone_types = [
    "agate",
    "amazonite",
    "amber",
    "amethyst",
    "aquamarine",
    "aventurine",
    "carnelian",
    "chalcedony",
    "citrine",
    "coral",
    "crystal",
    "diopside",
    "emerald",
    "garnet",
    "iolite",
    "jade",
    "kunzite",
    "kyanite",
    "labradorite",
    "lapis",
    "larimar",
    "malachite",
    "marcasite",
    "mixed-stone",
    "moissanite",
    "moonstone",
    "morganite",
    "onyx",
    "opal",
    "peridot",
    "prasiolite",
    "quartz",
    "rhodolite",
    "ruby",
    "sapphire",
    "shell",
    "spinel",
    "tanzanite",
    "tigereye",
    "topaz",
    "tourmaline",
    "tsavorite",
    "turquoise",
    "unakite",
    "zircon",
    "pearls",
    "diamond",
    "cubic_zirconia",
    "faux_emerald",
    "faux_ruby",
    "faux_sapphire",
    "other",
]

ross_simons_metal_types = [
    "gold",
    "sterling_silver",
    "gold_over_silver",
    "other_metal",
    "mixed_metal",
    "platinum",
    "stainless_steel",
]

superjeweler_stone_types = [
    "amethyst",
    "aquamarine",
    "black_diamond",
    "black_moissanite",
    "blue_diamond",
    "blue_topaz",
    "citrine",
    "cubic_zirconia",
    "diamond",
    "emerald",
    "garnet",
    "green_amethyst",
    "jade",
    "lab_grown_diamond",
    "lemon_quartz",
    "marcasite",
    "moissanite",
    "morganite",
    "mystic_topaz",
    "onyx",
    "opal",
    "pearl",
    "peridot",
    "pink_sapphire",
    "pink_topaz",
    "ruby",
    "sapphire",
    "smoky_quartz",
    "tanzanite",
]

superjeweler_metal_types = [
    "white_gold",
    "yellow_gold",
    "rose_gold",
    "platinum",
    "sterling_silver",
    "rose_gold_plated_silver",
]

reeds_stone_types = [
    "abalone_shell",
    "acetate",
    "agate",
    "amazonite",
    "amethyst",
    "aquamarine",
    "citrine",
    "crystal",
    "cubic_zirconia",
    "diamond",
    "doublet",
    "drusy",
    "emerald",
    "garnet",
    "glass",
    "hematite",
    "howlite",
    "lab_grown_diamond",
    "lapis",
    "magnesite",
    "mica",
    "morganite",
    "mother_of_pearl",
    "multi_stone",
    "no_stone",
    "onyx",
    "opal",
    "pearl",
    "peridot",
    "prasiolite",
    "quartz",
    "rhodolite_garnet",
    "ruby",
    "sapphire",
    "shell",
    "spinel",
    "swarovski_crystals",
    "tanzanite",
    "tigers_eye",
    "topaz",
    "tourmaline",
    "triplet",
    "turquoise",
]

reeds_metal_types = [
    "brass",
    "gold_filled",
    "gold_plated",
    "gold_tone",
    "gunmetal_plated",
    "platinum",
    "rhodium_plated",
    "rose_gold",
    "rose_gold_plated",
    "rose_gold_tone",
    "ruthenium_plated",
    "silver_tone",
    "stainless_steel",
    "sterling_silver",
    "tri-tone",
    "two-tone",
    "white_gold",
    "yellow_gold",
]

jomashop_stone_types = [
    "amethyst",
    "aquamarine",
    "black_diamond",
    "blue_topaz",
    "citrine",
    "cubic_zirconia",
    "diamond",
    "diopside",
    "emerald",
    "garnet",
    "gemstone",
    "jade",
    "moissanite",
    "moonstone",
    "morganite",
    "none",
    "opal",
    "other",
    "pearl",
    "peridot",
    "quartz",
    "rubellite",
    "ruby",
    "sapphire",
    "spinel",
    "tanzanite",
    "topaz",
    "turquoise",
]

jomashop_metal_types = [
    "brass",
    "gold",
    "gold_over_brass",
    "gold_over_silver",
    "gold_plated",
    "gold_plated_silver",
    "no_metal_type",
    "pewter",
    "platinum",
    "rhodium",
    "rose_gold",
    "silver",
    "silver_plated",
    "stainless_steel",
    "stainless_steel_white_gold",
    "sterling_silver",
    "sterling_silver_yellow_gold",
    "two-tone",
    "white_gold",
    "yellow_gold",
    "yellow_gold_plated",
    "yellow_gold_white_gold",
]

zales_items = {
    "name": "zales",
    "url": "https://www.zales.com/earrings/c/0104000000?q=*%3A_relevance_Ascending%3Agender_string%3ALADIES%3A{type}Types_string_mv%3A{material}&loadMore={page_number}",
    "selectors": zales_kay_jared_selectors,
    "stone_type": zales_kay_jared_stone_types,
    "metal_type": zales_kay_jared_metal_types,
}

kay_items = {
    "name": "kay",
    "url": "https://www.kay.com/earrings/womens-earrings/c/9000000197?q=*%3A_relevance_Ascending%3Agender_string%3AWOMEN%3A{type}Types_string_mv%3A{material}&loadMore={page_number}",
    "selectors": zales_kay_jared_selectors,
    "stone_type": zales_kay_jared_stone_types,
    "metal_type": zales_kay_jared_metal_types,
}

jared_items = {
    "name": "jared",
    "url": "https://www.jared.com/jewelry/earrings/c/7000000106?q=*%3A_relevance_Ascending%3Agender_string%3AWOMEN%3A{type}Types_string_mv%3A{material}&loadMore={page_number}",
    "selectors": zales_kay_jared_selectors,
    "stone_type": zales_kay_jared_stone_types,
    "metal_type": zales_kay_jared_metal_types,
}

ross_simons_items = {
    "name": "ross_simons",
    "url": "https://www.ross-simons.com/jewelry/earrings/?start={page_number}&sz=120",
    "selectors": {
        "product_boxes": ["div", {"class": "grid-tile"}],
        "product_on_sale": ["div", {"class": "price price-tier3"}],
        "product_href": ["a", {"class": "thumb-link rollover"}],
    },
}

jomashop_items = {
    "name": "jomashop",
    "url": "https://www.jomashop.com/jewelry.html?gender=Ladies&subtype=Earrings&p={page_number}",
    "selectors": {
        "product_boxes": ["div", {"class": "productItemBlock"}],
        "product_on_sale": ["div", {"class": "was-price-wrapper"}],
        "product_href": ["a", {"class": "productName-link"}],
    },
}

superjeweler_items = {
    "name": "superjeweler",
    "url": "https://www.superjeweler.com/earrings",
    "selectors": {
        "product_boxes": ["div", {"class": "sj-grid-element"}],
        "product_on_sale": ["p", {"class": "regular-price-value"}],
        "product_href": ["a", {"class": "short_desc_container"}],
    },
}

reeds_items = {
    "name": "reeds",
    "url": "https://www.reeds.com/jewelry/earrings/all-earrings.html?genders=Ladies&rfk=1",
    "selectors": {
        "product_boxes": ["div", {"class": "rfk_prodwrap"}],
        "product_on_sale": ["span", {"class": "original-price"}],
        "product_href": ["a", {"class": "rfk_container"}],
    },
}
