zales_kay_jared_selectors = {
    "product_boxes": ["div", {"class": "product-item-inner"}],
    "product_on_sale": ["div", {"class": "other-prices"}],
    "product_href": ["a", {"class": "thumb main-thumb"}],
    "image_src": ["img", {"class": "img-responsive with-border"}],
    "title": ["div", {"class": "name product-tile-description"}],
    "price": ["div", {"class": "price"}],
    "original_price": ["div", {"class": "original-price"}],
}


zales_kay_jared_stone_types = [
    "Diamond",
    "Lab+Created+Diamond",
    "No+Stone",
    "Morganite",
    "Sapphire",
    "Pearl",
    "Emerald",
    "Ruby",
    "Amethyst",
    "Topaz",
    "Opal",
    "Garnet",
    "Peridot",
    "Citrine",
    "Aquamarine",
    "Tanzanite",
    "Other",
    "Quartz",
    "Spinel",
    "Onyx",
    "Multi",
    "Alexandrite",
    "Cubic+Zirconia",
    "Apatite",
    "Crystal",
    "Cultured+Pearl",
    "Rhodolite",
    "Aquaprase",
    "Birthstone",
    "Chalcedony",
    "Moonstone",
    "Tourmaline",
    "Turquoise",
    "Zircon",
]

zales_kay_jared_metal_types = [
    "Gold",
    "Sterling+Silver",
    "Platinum",
    "Stainless+Steel",
]

ross_simons_stone_type_sub_class = [
    "gemstones",
    "diamond",
    "perals",
    "faux_stone",
    "other_stones",
]

ross_simons_stone_types = [
    "Agate",
    "Amber",
    "Amethyst",
    "Aquamarine",
    "Chalcedony",
    "Citrine",
    "Coral",
    "Emerald",
    "Garnet",
    "Jade",
    "Lapis",
    "Larimar",
    "Malachite",
    "Mixed-Stone",
    "Moissanite",
    "Moonstone",
    "Morganite",
    "Onyx",
    "Opal",
    "Peridot",
    "Prasiolite",
    "Quartz",
    "Rhodolite",
    "Ruby",
    "Sapphire",
    "Shell",
    "Spinel",
    "Tanzanite",
    "Topaz",
    "Tourmaline",
    "Turquoise",
    "Zircon",
    "Pearls",
    "Diamond",
    "Cubic+Zirconia",
    "Other+Stones",
]

ross_simons_metal_types = [
    "Gold",
    "Sterling+Silver",
    "Gold+Over+Silver",
    "Other+Metal",
    "Mixed+Metal",
    "Platinum",
    "Stainless+Steel",
]

superjeweler_stone_types = [
    "Amethyst",
    "Aquamarine",
    "Black+Diamond",
    "Black+Moissanite",
    "Blue+Diamond",
    "Blue+Topaz",
    "Citrine",
    "Cubic+Zirconia",
    "Diamond",
    "Emerald",
    "Garnet",
    "Green+Amethyst",
    "Jade",
    "Lab+Grown+Diamond",
    "Lemon+Quartz",
    "Marcasite",
    "Moissanite",
    "Morganite",
    "Mystic+Topaz",
    "Onyx",
    "Opal",
    "Pearl",
    "Peridot",
    "Pink+Sapphire",
    "Pink+Topaz",
    "Ruby",
    "Sapphire",
    "Smoky+Quartz",
    "Tanzanite",
]

superjeweler_metal_types = [
    "White+Gold",
    "Yellow+Gold",
    "Rose+Gold",
    "Platinum",
    "Sterling+Silver",
    "Rose+Gold+Plated+Silver",
]

reeds_stone_types = [
    "Abalone+Shell",
    "Amazonite",
    "Amethyst",
    "Aquamarine",
    "Citrine",
    "Crystal",
    "Cubic+Zirconia",
    "Diamond",
    "Doublet",
    "Drusy",
    "Emerald",
    "Garnet",
    "Glass",
    "Lab+Grown+Diamond",
    "Lapis",
    "Magnesite",
    "Morganite",
    "Mother+Of+Pearl",
    "Multi+Stone",
    "No+Stone",
    "Onyx",
    "Opal",
    "Pearl",
    "Peridot",
    "Quartz",
    "Rhodolite+Garnet",
    "Ruby",
    "Sapphire",
    "Spinel",
    "Swarovski+Crystals",
    "Tanzanite",
    "Topaz",
    "Turquoise",
]

reeds_metal_types = [
    "Brass",
    "Gold+Filled",
    "Gold+Plated",
    "Gold+Tone",
    "Gunmetal+Plated",
    "Platinum",
    "Rhodium+Plated",
    "Rose+Gold",
    "Rose+Gold+Plated",
    "Rose+Gold+Tone",
    "Ruthenium+Plated",
    "Silver+Tone",
    "Stainless+Steel",
    "Sterling+Silver",
    "Tri-Tone",
    "Two-Tone",
    "White+Gold",
    "Yellow+Gold",
]

jomashop_stone_types = [
    "Amethyst",
    "Aquamarine",
    "Black+Diamond",
    "Blue+Topaz",
    "Citrine",
    "Cubic+Zirconia",
    "Diamond",
    "Diopside",
    "Emerald",
    "Garnet",
    "Gemstone",
    "Jade",
    "Moissanite",
    "Moonstone",
    "Morganite",
    "None",
    "Opal",
    "Other",
    "Pearl",
    "Peridot",
    "Quartz",
    "Rubellite",
    "Ruby",
    "Sapphire",
    "Spinel",
    "Tanzanite",
    "Topaz",
    "Turquoise",
]

jomashop_metal_types = [
    "Brass",
    "Gold",
    "No+Metal+Type",
    "Pewter",
    "Platinum",
    "Rhodium",
    "Rose+Gold",
    "Silver",
    "Silver+Plated",
    "Stainless+Steel",
    "Sterling+Silver",
    "Two-Tone",
    "White+Gold",
    "Yellow+Gold",
]

zales_items = {
    "name": "zales",
    "url": "https://www.zales.com/earrings/c/0104000000?q=*%3A_relevance_Ascending%3Agender_string%3ALADIES%3A{type}Types_string_mv%3A{material}&loadMore={page_number}",
    "selectors": zales_kay_jared_selectors,
    "stone_type": zales_kay_jared_stone_types,
    "metal_type": zales_kay_jared_metal_types,
}

kay_items = {
    "name": "kay",
    "url": "https://www.kay.com/earrings/womens-earrings/c/9000000197?q=*%3A_relevance_Ascending%3Agender_string%3AWOMEN%3A{type}Types_string_mv%3A{material}&loadMore={page_number}",
    "selectors": zales_kay_jared_selectors,
    "stone_type": zales_kay_jared_stone_types,
    "metal_type": zales_kay_jared_metal_types,
}

jared_items = {
    "name": "jared",
    "url": "https://www.jared.com/jewelry/earrings/c/7000000106?q=*%3A_relevance_Ascending%3Agender_string%3AWOMEN%3A{type}Types_string_mv%3A{material}&loadMore={page_number}",
    "selectors": zales_kay_jared_selectors,
    "stone_type": zales_kay_jared_stone_types,
    "metal_type": zales_kay_jared_metal_types,
}

ross_simons_items = {
    "name": "ross_simons",
    "url": "https://www.ross-simons.com/jewelry/earrings/?prefn1={type}1&prefv1={material}&srule=sales-rank&start={page_number}&sz=120",
    "url_gemstone": "https://www.ross-simons.com/jewelry/earrings/?prefn1=stone2&prefv1=Gemstones%3B{material}&srule=sales-rank&start={page_number}&sz=120",
    "url_faux": "https://www.ross-simons.com/jewelry/earrings/?prefn1=stone2&prefv1=Faux%20Stone%3BCubic+Zirconia&srule=sales-rank&start={page_number}&sz=120",
    "selectors": {
        "product_boxes": ["div", {"class": "grid-tile"}],
        "product_on_sale": ["div", {"class": "price price-tier3"}],
        "product_href": ["a", {"class": "thumb-link rollover"}],
        "image_src": [
            "img",
            {"class": "c-product-tile__image-src lazy rollover-main-image"},
        ],
        "title": ["div", {"class": "product-name"}],
        "price": ["span", {"class": "c-product-pricing__sales__price"}],
        "original_price": ["div", {"class": "price price-tier3"}],
    },
    "stone_type": ross_simons_stone_types,
    "metal_type": ross_simons_metal_types,
}

jomashop_items = {
    "name": "jomashop",
    "url": "https://www.jomashop.com/filters/jewelry?gender=Ladies&subtype=Earrings&{type}_type={material}&p={page_number}",
    "selectors": {
        "product_boxes": ["div", {"class": "productItemBlock"}],
        "product_on_sale": ["div", {"class": "was-price-wrapper"}],
        "product_href": ["a", {"class": "productName-link"}],
        "image_src": ["img", {"class": "productImg"}],
        "title": ["span", {"class": "name-out-brand"}],
        "price": ["div", {"class": "now-price"}],
        "original_price": ["div", {"class": "was-wrapper"}],
    },
    "stone_type": jomashop_stone_types,
    "metal_type": jomashop_metal_types,
}

superjeweler_items = {
    "name": "superjeweler",
    "url": "https://www.superjeweler.com/earrings",
    "selectors": {
        "product_boxes": ["div", {"class": "sj-grid-element"}],
        "product_on_sale": ["p", {"class": "regular-price-value"}],
        "product_href": ["a", {"class": "short_desc_container"}],
        "image_src": ["img", {"class": "star fadeIn"}],
        "title": ["h6", {"class": "t-dgrey md-mb0 sm-mb0 xs-mb0"}],
        "price": ["p", {"class": "our-price-value"}],
        "original_price": ["p", {"class": "regular-price-value"}],
    },
    "stone_type": superjeweler_stone_types,
    "metal_type": superjeweler_metal_types,
}

reeds_items = {
    "name": "reeds",
    "url": "https://www.reeds.com/jewelry/earrings/all-earrings.html?{type}={material}&genders=Ladies&rfk=1",
    "selectors": {
        "product_boxes": ["div", {"class": "rfk_prodwrap"}],
        "product_on_sale": ["span", {"class": "original-price"}],
        "product_href": ["a", {"class": "rfk_container"}],
        "image_src": ["img", {"class": "rfk_image1"}],
        "title": ["span", {"itemprop": "name"}],
        "price": ["span", {"class": "final-price"}],
        "original_price": ["span", {"class": "original-price"}],
    },
    "stone_type": reeds_stone_types,
    "metal_type": reeds_metal_types,
}
